name: CodeQL Analysis

on:
  push:
    branches:
      - main

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [go]  # Add other languages as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Build and run tests
        run: |
          go build -v
          go test -v ./...

      - name: Run CodeQL Analysis
        id: codeql
        uses: github/codeql-action/analyze@v1

  dashboard:
    runs-on: ubuntu-latest
    needs: codeql-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Upload CodeQL results to GitHub Dashboard
        uses: github/codeql-action/upload-github-dashboard@v1
        with:
          results: ${{ steps.codeql.outputs.results-path }}
