name: Go SonarQube

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install SonarQube Scanner
      run: |
        curl -o sonar-scanner-cli.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli.zip
        export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin
        rm sonar-scanner-cli.zip

    - name: Build and run tests
      run: |
        go build -v
        go test -v ./...

    - name: SonarQube analysis
      run: |
        sonar-scanner \
          -Dsonar.host.url=http://your-sonarqube-instance:9000/ \
          -Dsonar.login=your-sonarqube-token \
          -Dsonar.projectKey=your-project-key \
          -Dsonar.projectName=your-project-name \
          -Dsonar.sources=.
