name: Go SonarQube

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install SonarQube Scanner
      run: |
        curl -o sonar-scanner-cli.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli.zip
        sudo mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
        rm sonar-scanner-cli.zip
        echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> ~/.bashrc
        source ~/.bashrc

    - name: Build and run tests
      run: |
        go build -v
        go test -v ./...

    - name: SonarQube analysis
      run: |
        /opt/sonar-scanner/bin/sonar-scanner \
           -Dsonar.host.url=http://13.234.10.249:9000/ \
           -Dsonar.login=9e23f8950040cdfd17b07e75a4a053c1f88e7a66 \
           -Dsonar.projectKey=golang \
           -Dsonar.projectName=golang \
           -Dsonar.sources=.
